### ISSUE TITLE
create_manifest_bulk.py not working with py3

### ISSUE THREAD

**Issue by sclan** [dnanexus/dxda#11]
Issue1:
The dxda was cloned just now.
```
$ python -V
Python 3.7.3
```

```
$ python create_manifest_bulk.py -r --outfile "myfiles.manifest.json.bz2" project-FXB0v500ypGV9FGK2Fyk208b:/
Traceback (most recent call last):
  File "create_manifest_bulk.py", line 59, in <module>
    main()
  File "create_manifest_bulk.py", line 53, in main
    f.write(bz2.compress(json.dumps(manifest, indent=2, sort_keys=True)))
  File "/home/slan/anaconda3/lib/python3.7/bz2.py", line 334, in compress
    return comp.compress(data) + comp.flush()
TypeError: a bytes-like object is required, not 'str'
```

Issue2:
The example in  the Readme.md for newly added manifest creation instructions:
https://github.com/dnanexus/dxda/blob/master/README.md

`python create_manifest_bulk.py --folder "Project:/Folder" --recursive --outfile "myfiles.manifest.json.bz2"`

When run `$ python create_manifest_bulk.py -h`, the syntax for the command is
usage: create_manifest_bulk.py [-h] [--outfile OUTFILE] [-r] folder

There is no "--folder" argument. Looks like the following command is supposed to work:
`python create_manifest_bulk.py --recursive --outfile "myfiles.manifest.json.bz2" Project:/Folder`

Currently the following command works as expected (manifest file generated) in py2.7 environment:
$GOROOT/bin/go run $GOROOT/src/github.com/dnanexus/dxda/cmd/dx-download-agent download ./myfiles.manifest.json.bz2 <project-ID>:/

**Comment by sclan** [comment]
Later version of dxda fixed it. Closing.
