### ISSUE TITLE
Give more descriptive error message when invalid token used

### ISSUE THREAD

**Issue by mjhipp** [dnanexus/dxda#33]
When using the dxda with a token that does not exist or has expired, the following error shows (replaced part of addresses with `...`):

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x...]
goroutine 53 [running]:
github.com/dnanexus/dxda.DxAPI(0x9..., 0xc000..., 0xc00..., 0xa, 0xc00..., 0xc00..., 0x26, 0xc00..., 0x45, 0x0, ...)
  	/go/src/github.com/dnanexus/dxda/dx_http.go:383 +0x57c
github.com/dnanexus/dxda.(*State).createURL(0xc0..., 0xc0..., 0x1d, 0xc0..., 0x20, 0xc0..., 0xc, 0xc0..., 0x32, 0x1, ...)
 	/go/src/github.com/dnanexus/dxda/dxda.go:693 +0x286
github.com/dnanexus/dxda.(*State).preauthUrlsWorker(0xc0..., 0xc0..., 0xc00...)
 	/go/src/github.com/dnanexus/dxda/dxda.go:722 +0x2a1
created by github.com/dnanexus/dxda.(*State).DownloadManifestDB
	/go/src/github.com/dnanexus/dxda/dxda.go:853 +0x6f3
 
```

Took some investigation to realize this was from an invalid token. A more descriptive error message in this case would be helpful.

**Comment by mjhipp** [comment]
Fixed by #36 

Thanks!
