### ISSUE TITLE
fatal error: concurrent map read and map writerts

### ISSUE THREAD

**Issue by jgrundstad** [dnanexus/dxda#8]
Greetings,

I experienced this error today, and have included a portion of the total error output.

Please let me know if I can provide anything else. Thanks!

```
$ ../bin/dx-download-agent-linux/dx-download-agent download -max_threads=24 manifests/manifest.json.bz2
Logging detailed output to: manifests/manifest.json.bz2.download.log

Obtained token using environment
Required disk space = 6.5TB, available = 1798.7TB
Preparing files for download
Downloading files using 24 threads
fatal error: concurrent map read and map writerts (~187.1 MB/s written to disk estimated over the last 60s)

goroutine 86 [running]:
runtime.throw(0x826afe, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0010cdce0 sp=0xc0010cdcb0 pc=0x435982
runtime.mapaccess2_faststr(0x7bcf80, 0xc00c310f60, 0xc0127388a0, 0x1d, 0xc012733d00, 0x1d)
        /usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc0010cdd50 sp=0xc0010cdce0 pc=0x41cf98
github.com/dnanexus/dxda.worker(0xc, 0xc0000b8540, 0xc00001806d, 0x20, 0xcef8e8, 0xc0037666d0)
        /go/src/github.com/dnanexus/dxda/dxda.go:543 +0x1af fp=0xc0010cdfb0 sp=0xc0010cdd50 pc=0x6bf97f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0010cdfb8 sp=0xc0010cdfb0 pc=0x461df1
created by github.com/dnanexus/dxda.DownloadManifestDB
        /go/src/github.com/dnanexus/dxda/dxda.go:653 +0x605

goroutine 1 [semacquire, 18 minutes]:
sync.runtime_Semacquire(0xc0037666d8)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0037666d0)
        /usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/dnanexus/dxda.DownloadManifestDB(0x7ffddde38b09, 0x28, 0xc00001806d, 0x20, 0x18)
        /go/src/github.com/dnanexus/dxda/dxda.go:658 +0x68a
main.(*downloadCmd).Execute(0xc00001a4e8, 0x878180, 0xc00001a0c0, 0xc0000b83c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/dnanexus/dxda/cmd/dx-download-agent/dx-download-agent.go:64 +0x3a4
github.com/google/subcommands.(*Commander).Execute(0xc00014c000, 0x878180, 0xc00001a0c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/google/subcommands/subcommands.go:142 +0x2fa
github.com/google/subcommands.Execute(0x878180, 0xc00001a0c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/google/subcommands/subcommands.go:420 +0x5f
main.main()
        /go/src/github.com/dnanexus/dxda/cmd/dx-download-agent/dx-download-agent.go:143 +0x141

goroutine 90 [runnable]:
net/http.Header.clone(0xc0065605d0, 0x0)
        /usr/local/go/src/net/http/header.go:69 +0xcd
net/http.(*Client).makeHeadersCopier(0xc0065603c0, 0xc0134de000, 0x0)
        /usr/local/go/src/net/http/client.go:671 +0x44
net/http.(*Client).do(0xc0065603c0, 0xc0134de000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:530 +0x12d
net/http.(*Client).Do(0xc0065603c0, 0xc0134de000, 0x877940, 0xc0128bc020, 0x0)
        /usr/local/go/src/net/http/client.go:509 +0x35
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000471840, 0xc013100040, 0xf, 0xc0128b1d80, 0x20)
        /go/src/github.com/hashicorp/go-retryablehttp/client.go:377 +0xad
github.com/dnanexus/dxda.makeRequestWithHeadersFail(0x81d056, 0x3, 0xc013642000, 0x7c, 0xc000471ad0, 0xc005cbe030, 0x2, 0x8, 0x7c, 0xc01332b2c0, ...)
        /go/src/github.com/dnanexus/dxda/dxda.go:186 +0x258
github.com/dnanexus/dxda.DownloadDBPart(0x7ffddde38b09, 0x28, 0xc012737640, 0x1d, 0xc012737660, 0x20, 0xc003c257d0, 0x21, 0xc012737680, 0x11, ...)
        /go/src/github.com/dnanexus/dxda/dxda.go:775 +0x564
github.com/dnanexus/dxda.recoverer(0xffffffffffffffff, 0x833f60, 0x7ffddde38b09, 0x28, 0xc012737640, 0x1d, 0xc012737660, 0x20, 0xc003c257d0, 0x21, ...)
        /go/src/github.com/dnanexus/dxda/dxda.go:586 +0x163
github.com/dnanexus/dxda.worker(0x10, 0xc0000b8540, 0xc00001806d, 0x20, 0xcef8e8, 0xc0037666d0)
        /go/src/github.com/dnanexus/dxda/dxda.go:555 +0x107
created by github.com/dnanexus/dxda.DownloadManifestDB
        /go/src/github.com/dnanexus/dxda/dxda.go:653 +0x605

goroutine 89 [semacquire]:   
sync.runtime_SemacquireMutex(0xcef8ec, 0x3cad4cfac5fd2b00)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xcef8e8) 
        /usr/local/go/src/sync/mutex.go:134 +0xff
github.com/dnanexus/dxda.DownloadDBPart(0x7ffddde38b09, 0x28, 0xc0127383c0, 0x1d, 0xc0127383e0, 0x20, 0xc003c25a10, 0x21, 0xc012738400, 0x11, ...)
        /go/src/github.com/dnanexus/dxda/dxda.go:768 +0x2fb
github.com/dnanexus/dxda.recoverer(0xffffffffffffffff, 0x833f60, 0x7ffddde38b09, 0x28, 0xc0127383c0, 0x1d, 0xc0127383e0, 0x20, 0xc003c25a10, 0x21, ...)
        /go/src/github.com/dnanexus/dxda/dxda.go:586 +0x163
github.com/dnanexus/dxda.worker(0xf, 0xc0000b8540, 0xc00001806d, 0x20, 0xcef8e8, 0xc0037666d0)
        /go/src/github.com/dnanexus/dxda/dxda.go:555 +0x107
created by github.com/dnanexus/dxda.DownloadManifestDB
        /go/src/github.com/dnanexus/dxda/dxda.go:653 +0x605

```

**Comment by geetduggal** [comment]
Hi Jason,

Could you try release v0.2.0 and see if this fixes this issue for you?  Thanks in advance!

**Comment by jgrundstad** [comment]
It may have been to me hogging bandwidth, and an admin killing the job.  I'm running in a new location without issue - so far.  If I do see this happen again I'll be sure to try the most updated version of the software.  Thanks!

**Comment by geetduggal** [comment]
👍 Someone else ran into this as well, which is why I cut the v0.2.0 release.  Happy downloading and Christmas!  Do not hesitate to keep us posted and we will try to address any issues ASAP.

**Comment by orodeh** [comment]
This seems to have been resolved.
